# name: Deploy Nginx

# on:
#   push:
#     branches:
#     - 'main'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     env:
#       IMAGE_TAG: ${{ github.sha }}
#     steps:

#     - name: code checkout
#       uses: actions/checkout@v2

#     - name: install the gcloud cli
#       uses: google-github-actions/setup-gcloud@v0
#       with:
#         project_id: ${{ secrets.GCP_PROJECT_ID }}
#         service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
#         install_components: 'gke-gcloud-auth-plugin'
#         export_default_credentials: true

#     - name: build and push the docker image
#       env:
#         GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
#       run: |
#         gcloud auth configure-docker europe-central2-docker.pkg.dev
#         docker build -t europe-central2-docker.pkg.dev/task-management-app-430719/test/tma_front_image:$IMAGE_TAG .
#         docker push europe-central2-docker.pkg.dev/task-management-app-430719/test/tma_front_image:$IMAGE_TAG

#     - name: deploy to gke
#       env:
#         GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
#       run: |
#         gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
#         sed -i "s/GOOGLE_PROJECT/$GCP_PROJECT_ID/g" resources.yaml
#         kubectl apply -f resources.yaml

name: Deploy to Kubernetes
on:
  push:
    branches:
      - "main"
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_TF_STATE_BUCKET_NAME: ${{ secrets.GCP_TF_STATE_BUCKET }}
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
jobs:
  deploy: 
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authentciate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/521742582292/locations/global/\
          workloadIdentityPools/gh-identity-pool/providers/gh-provider'
          service_account: 'github-860@task-management-app-430719.iam.gserviceaccount.com'
      - name: Docker auth
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev
      - name: Build and push Docker image
        run: |
          docker build -t europe-central2-docker.pkg.dev/task-management-app-430719/test/tma_front_image:$IMAGE_TAG .
          sudo -u docker push europe-central2-docker.pkg.dev/task-management-app-430719/test/tma_front_image:$IMAGE_TAG
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        run: terraform init -backend-config="bucket=$GCP_TF_STATE_BUCKET_NAME" -frontend-config="prefix=k8s"
        working-directory: terraform
      - name: Terraform Plan
        run: |
          terraform plan \
          -var="region=europe-central1" \
          -var="project_id=task-management-app-430719" \
          -var="container_image=europe-central2-docker.pkg.dev/task-management-app-430719/tma_front_image:$IMAGE_TAG" \
          -out=PLAN
        working-directory: terraform
      - name: Terraform apply
        run: terform apply PLAN